// ==========================================  Importing Libraries  =========================================

import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';


// ---------------------------  Importing Animateable and Linear Gradient Libraries

import * as Animatable from 'react-native-animatable';
import LinearGradient from 'react-native-linear-gradient';

import Icon from 'react-native-vector-icons/Entypo';

// ==========================================  Creating a Component  ========================================

const TermAndCondition = ({navigation}) => {
    return (
        <LinearGradient
            start={{ x: 1, y: 0.3 }}
            end={{ x: 0, y: 1 }}
            colors={['#9e4bff', '#7f00ff']}
            style={styles.container}>

            {/* ---------------------------  Header  */}

            <TouchableOpacity onPress={() => navigation.goBack()}>
                <Icon name='circle-with-cross' size={25} color='#fff' style={{position: 'absolute', top: 10, right: 10}}/>
            </TouchableOpacity>

            <View style={styles.header}>
                <Text style={styles.textHeader}>Terms & Condition</Text>
                <Text style={{ color: '#fff' }}>Updated at 2022-02-06</Text>
            </View>

            <Animatable.View
                animation="fadeInUpBig" style={styles.footer}>

                <ScrollView showsVerticalScrollIndicator={false}>

{/* --------------------------------  General Terms */}

                    <Text style={styles.heading}>General Terms</Text>
                    <Text style={styles.text}>By accessing and placing an order with, you confirm that you are in agreement with and bound by the terms of service contained in
                        the Terms & Conditions outlined below.</Text>


{/* --------------------------------  License */}

                    <Text style={styles.heading}>License</Text>
                    <Text style={styles.text}>Cure Zone grants you a revocable, non-exclusive, non- transferable, limited license to download, install and use our service strictly
                        in accordance with the terms of this Agreement.</Text>

                    <Text style={styles.text}>These Terms & Conditions are a contract between you and Cure Zone (referred to in these Terms & Conditions as "Cure Zone", "us",
                        "we" or "our"), the provider of the Cure Zone website and the services accessible from the Cure Zone website (which are collectively
                        referred to in these Terms & Conditions as the "Cure Zone Service").</Text>

                    <Text style={styles.text}>You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the
                        Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of
                        these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.</Text>


{/* --------------------------------  Defination and Key Terms */}

                    <Text style={styles.heading}>Definations and Key Terms</Text>
                    <Text style={styles.subHeading}>For this Terms & Conditions:</Text>

                    <Text style={styles.text}>• Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                        provide analytics, remember information about you such as your language preference or login information.</Text>

                    <Text style={styles.text}>• Company: when this policy mentions "Company," "we," "us," or "our," it refers to Cure Zone that is responsible for your
                        information under this Privacy Policy.</Text>

                    <Text style={styles.text}>• Country: where Cure Zone or the owners/founders of Cure Zone are based, in this case is Pakistan.</Text>

                    <Text style={styles.text}>• Customer: refers to the company, organization or person that signs up to use the Cure Zone Service to manage the
                        relationships with your consumers or service users.</Text>

                    <Text style={styles.text}>• Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Cure
                        Zone and use the services.</Text>

                    <Text style={styles.text}>• IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These
                        numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a
                        device is connecting to the Internet.</Text>

                    <Text style={styles.text}>• Personnel: refers to those individuals who are employed by Cure Zone or are under contract to perform a service on behalf of
                        one of the parties.</Text>

                    <Text style={styles.text}>• Personal Data: any information that directly, indirectly, or in connection with other information - including a personal
                        identification number - allows for the identification or identifiability of a natural person.</Text>

                    <Text style={styles.text}>• Service: refers to the service provided by Cure Zone as described in the relative terms (if available) and on this platform.</Text>

                    <Text style={styles.text}>• Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our
                        content or whose products or services we think may interest you.</Text>

                    <Text style={styles.text}>• Website: Cure Zone's site, which can be accessed via this URL:</Text>

                    <Text style={styles.text}>• You: a person or entity that is registered with Cure Zone to use the Services.</Text>


{/* --------------------------------  Contact */}

                    <Text style={styles.heading}>Don't hesitate to contact us if you have any questions.</Text>
                    <Text style={styles.text}>• Via Email: ub22444@gmail.com</Text>


                </ScrollView>
            </Animatable.View>

        </LinearGradient>
    );
}


// ==========================================  Styling  ====================================================

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flex: 0.5,
        justifyContent: 'flex-end',
        paddingBottom: 20,
        paddingHorizontal: 20,
    },
    footer: {
        flex: 3,
        backgroundColor: '#fff',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 20,
        paddingVertical: 30
    },
    textHeader: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 30,
        // fontFamily: 'Montserrat-SemiBold'
    },
    heading: {
        fontSize: 16,
        fontFamily: 'Montserrat-SemiBold',
        color: '#7f00ff',
    },
    subHeading: {
        fontSize: 14,
        fontFamily: 'Montserrat-SemiBold',
        color: '#7f00ff'
    },
    text: {
        color: '#7b54f2',
        paddingBottom: 6,
    }
});


// ----------------------------  Exporting the App

export default TermAndCondition;